//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockUniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.ContactsDetails = new HashSet<ContactsDetail>();
        }
    
        public int Contact_ID { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<ContactsDetail> ContactsDetails { get; set; }
    }
}
