//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockUniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactsDetail
    {
        public int Feedback_ID { get; set; }
        public int Contact_ID { get; set; }
        public int Employee_ID { get; set; }
        public string Title { get; set; }
        public string Feedback_Detail { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Feedback_Reply { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
