//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace ClockUniverse
{
   
    public partial class Order
    {
        public Order()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }

        public int Order_ID { get; set; }
        public System.DateTime Order_Date { get; set; }
        public System.DateTime Delivery_Date { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập Họ tên khách hàng")]
        public string Customer_Name { get; set; }
        
        [StringLength(12, ErrorMessage = "Số điện thoại phải từ 9-12 số")]
        [Required(ErrorMessage = "Bạn chưa nhập Số điện thoại")]
        [Range(9, Int64.MaxValue, ErrorMessage = "Số điện thoại phải từ 9-12 số")]
        public string Customer_Phone { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập Email")]
        public string Customer_Email { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập Địa chỉ giao hàng")]
        public string Deliver_Address { get; set; }
        public int Deliver_Status { get; set; }
        public Nullable<System.DateTime> Order_ChangeDate { get; set; }
        public decimal Total_Price { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
    }
}
